default: true

# Disable line-length checking
MD013: false

# Allow duplicate headings in distinct sections
MD024:
  allow_different_nesting: true

# Allow inline HTML
MD033: false

# Allow emphasis used as heading
MD036: false
